version: "3.9"
services:
  db_test:
    container_name: "db_test"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_test
    ports:
      - "5433:5432"
    networks:
      - custom

  redis_test:
    container_name: "redis_test"
    image: redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - custom

networks:
  custom:
    driver: bridge