version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - custom

  app:
    container_name: "app"
    image: app
    build:
      context: .
    command: bash -c "./run.sh && cd src && uvicorn main:app --host 0.0.0.0"
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - custom

networks:
  custom:
    driver: bridge