upstream backend {
    server 0.0.0.0:8000;
}

server {
    listen 80;
    location / {
            root /usr/share/nginx/html;
        }
#         location ~\.(css)$ {
#             root /usr/share/nginx/html/css;
#         }
#         location ~\.(js|map)$ {
#             root /usr/share/nginx/html/js;
#         }
    location /api/ {
        proxy_pass http://backend;
    }
}