"""Add field name to users

Revision ID: 2932ae0309bd
Revises: 9563d964bae0
Create Date: 2023-09-20 11:40:42.233010

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2932ae0309bd"
down_revision = "9563d964bae0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tweets", "archive")
    op.add_column("users", sa.Column("name", sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    op.add_column(
        "tweets",
        sa.Column("archive", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
