"""Nullable False for tweet_ids in files

Revision ID: 43c2188f8a7d
Revises: c597ba20a8fa
Create Date: 2023-09-23 13:35:15.151946

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43c2188f8a7d"
down_revision = "c597ba20a8fa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files", "tweet_ids", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files", "tweet_ids", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
